
- name: Delete if temporary host file already exists.
  ansible.builtin.file:
    path: /tmp/ansible_hosts
    state: absent
- name: Write lines to the temorary host file.
  ansible.builtin.blockinfile: 
    path: /tmp/ansible_hosts
    create: yes
    insertafter: EOF
    block: |
      192.0.2.50
      aserver.example.org
      bserver.example.org
- name: Copy the temporary file and backup the old one.
  ansible.builtin.copy: 
      src: /tmp/ansible_hosts
      dest: /tmp/ansible_hosts2
      backup: yes
- name: Execute the commands.
  command: "ansible-playbook ./my_task.yaml"
- name: Loop through items
  ansible.builtin.lineinfile:
    path: /tmp/ansible_counter
    create: yes
    insertafter: EOF
    line: "Countdown {{ item }} "
  loop:
      - 5
      - 4
      - 3
      - 2
      - 1

                    






# - name: Install sublime
#   apt:
#     name: sublime
#     state: present
#   tags: sublime





# - name: Add an Apt signing key, will not download if present
#   ansible.builtin.apt_key:
#     id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
#     url: https://download.sublimetext.com/sublimehq-pub.gpg
#     state: present

# # sudo apt-get install apt-transport-https


# - name: Remove a Apt specific signing key, leading 0x is valid
#   ansible.builtin.apt_key:
#     id: 0x9FED2BCBDCD29CDF762678CBAED4B06F473041FA
#     state: absent

# echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# - name: Add an Apt signing key to a specific keyring file
#   ansible.builtin.apt_key:
#     id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
#     url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
#     keyring: /etc/apt/trusted.gpg.d/debian.gpg

# - name: Add Apt signing key on remote server to keyring
#   ansible.builtin.apt_key:
#     id: 9FED2BCBDCD29CDF762678CBAED4B06F473041FA
#     file: /tmp/apt.gpg
#     state: present


# - name: Update repositories cache and install "sublime" package
#   ansible.builtin.apt:
#     name: sublime
#     update_cache: yes

# - name: Run the equivalent of "apt-get update" as a separate step
#   ansible.builtin.apt:
#     update_cache: yes


# - name: Remove "sublime" package
#   ansible.builtin.apt:
#     name: sublime
#     state: absent


# - name: Install the version '4' of package "sublime-text"
#   ansible.builtin.apt:
#     name: sublime-text=1.00


# - name: Remove useless packages from the cache
#   ansible.builtin.apt:
#     autoclean: yes

# - name: Remove dependencies that are no longer required
#   ansible.builtin.apt:
#     autoremove: yes

# - name: Run the equivalent of "apt-get clean" as a separate step
#   apt:
#     clean: yes


# # - name: Configure sublime file
# #   copy:
# #     src: ntp.conf.j2
# #     dest: /etc/ntp.conf
# #   tags: ntp
# #   notify: restart ntp


# # - name: test to see if sublime is installed
# #   command: getenforce
# #   register: sestatus
# #   changed_when: false
